import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "he";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.experiences": "Experiences",
    "nav.gallery": "Gallery",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.personal": "Personal",
    "nav.eliteJourneys": "Elite Journeys",
    "nav.privateFlights": "Private Flights",
    "nav.boutique": "Boutique",
    "nav.requestQuote": "Request Quote",
    
    // Hero Section
    "hero.tagline": "Luxury Travel Experiences",
    "hero.discover": "Discover",
    "hero.description": "Your worldwide travel partner – crafting unforgettable journeys across our curated destinations.",
    "hero.cta.plan": "Plan Your Journey",
    "hero.cta.explore": "Explore Experiences",
    "hero.cta.story": "Discover Our Story",
    "hero.scroll": "Scroll",
    
    // Hero Slides
    "hero.slide1.headline": "Well Travelled",
    "hero.slide1.subheadline": "Experience the Art of Indulgence",
    "hero.slide1.description": "Our luxury travel advisors deliver exceptionally indulgent experiences wherever life takes you.",
    "hero.slide2.headline": "La Dolce Vita",
    "hero.slide2.subheadline": "Tuscany Awaits You",
    "hero.slide2.description": "Savor the rich flavors of Tuscany, from world-class vineyards to authentic culinary experiences.",
    "hero.slide3.headline": "Alpine Excellence",
    "hero.slide3.subheadline": "Where Performance Meets Scenery",
    "hero.slide3.description": "Private alpine journeys through Austria and Italy, combining iconic mountain roads with luxury.",
    "hero.slide4.headline": "Desert Serenity",
    "hero.slide4.subheadline": "Modern Elegance Meets Timeless Stillness",
    "hero.slide4.description": "Experience the refined blend of modern luxury and the tranquil beauty of the desert.",
    "hero.slide5.headline": "Island Paradise",
    "hero.slide5.subheadline": "Crystal Waters Await",
    "hero.slide5.description": "Discover pristine beaches and warm hospitality across the Philippine archipelago.",
    
    // Stats Section
    "stats.years": "Years of Experience",
    "stats.destinations": "Destinations Worldwide",
    "stats.travelers": "Happy Travelers",
    "stats.satisfaction": "Client Satisfaction",
    "stats.valuesTagline": "What We Stand For",
    "stats.valuesTitle": "Our Core Values",
    "stats.passion": "Passion",
    "stats.passion.desc": "We love what we do and it shows in every journey we create.",
    "stats.excellence": "Excellence",
    "stats.excellence.desc": "Uncompromising quality in every detail, every destination.",
    "stats.trust": "Trust",
    "stats.trust.desc": "Your safety and satisfaction are our highest priorities.",
    "stats.exclusivity": "Exclusivity",
    "stats.exclusivity.desc": "Access to unique experiences you won't find anywhere else.",
    
    // Destinations
    "dest.greece": "Greece",
    "dest.greece.tagline": "Where myths come alive",
    "dest.italy": "Italy",
    "dest.italy.tagline": "La dolce vita awaits",
    "dest.poland": "Poland",
    "dest.poland.tagline": "Historic charm unveiled",
    "dest.austria": "Austria",
    "dest.austria.tagline": "Alpine elegance",
    "dest.uae": "UAE",
    "dest.uae.tagline": "Modern luxury redefined",
    "dest.srilanka": "Sri Lanka",
    "dest.srilanka.tagline": "Island of wonders",
    "dest.philippines": "Philippines",
    "dest.philippines.tagline": "Tropical paradise",
    "dest.worldwide": "Worldwide",
    "dest.worldwide.tagline": "Global adventures",
    
    // Destinations Showcase
    "destinations.tagline": "Our Destinations",
    "destinations.title": "Discover Our World",
    "destinations.highlights": "Highlights",
    "destinations.greece.desc": "Ancient ruins, sun-kissed islands, and Mediterranean magic await in the birthplace of Western civilization.",
    "destinations.greece.h1": "Santorini sunsets",
    "destinations.greece.h2": "Athens history",
    "destinations.greece.h3": "Island hopping",
    "destinations.italy.desc": "From Renaissance art to coastal glamour, experience la dolce vita in every corner of this timeless destination.",
    "destinations.italy.h1": "Amalfi Coast",
    "destinations.italy.h2": "Tuscan vineyards",
    "destinations.italy.h3": "Roman heritage",
    "destinations.poland.desc": "Discover medieval cities, pristine nature, and warm hospitality in the heart of Central Europe.",
    "destinations.poland.h1": "Krakow old town",
    "destinations.poland.h2": "Mountain retreats",
    "destinations.poland.h3": "Cultural treasures",
    "destinations.austria.desc": "Alpine grandeur meets imperial elegance in this symphony of nature and refined culture.",
    "destinations.austria.h1": "Vienna palaces",
    "destinations.austria.h2": "Alpine skiing",
    "destinations.austria.h3": "Musical heritage",
    "destinations.uae.desc": "Where ancient traditions meet futuristic luxury in the world's most ambitious destination.",
    "destinations.uae.h1": "Dubai skyline",
    "destinations.uae.h2": "Desert adventures",
    "destinations.uae.h3": "World-class shopping",
    "destinations.srilanka.desc": "Tropical beaches, ancient temples, and wildlife encounters on this teardrop island paradise.",
    "destinations.srilanka.h1": "Tea plantations",
    "destinations.srilanka.h2": "Wildlife safaris",
    "destinations.srilanka.h3": "Ancient temples",
    "destinations.philippines.desc": "Crystal waters, pristine beaches, and warm Filipino hospitality across 7,000 islands.",
    "destinations.philippines.h1": "Palawan islands",
    "destinations.philippines.h2": "Diving paradise",
    "destinations.philippines.h3": "Beach resorts",
    "destinations.worldwide.desc": "Beyond our featured destinations, we craft bespoke journeys to any corner of the globe.",
    "destinations.worldwide.h1": "Custom Itineraries",
    "destinations.worldwide.h2": "Group Tours",
    "destinations.worldwide.h3": "Luxury Escapes",
    
    // Services Preview
    "services.tagline": "Our Services",
    "services.title": "Exceptional Travel Services",
    "services.description": "From personalized itineraries to exclusive access, we handle every detail of your luxury journey.",
    "services.cta": "View All Services",
    "services.custom.title": "Custom Itineraries",
    "services.custom.desc": "Bespoke travel plans tailored to your preferences",
    "services.concierge.title": "24/7 Concierge",
    "services.concierge.desc": "Round-the-clock support throughout your journey",
    "services.access.title": "Exclusive Access",
    "services.access.desc": "VIP experiences and private tours",
    "services.accommodations.title": "Luxury Accommodations",
    "services.accommodations.desc": "Hand-selected hotels and private villas",
    
    // Experiences Preview
    "experiences.tagline": "Curated Experiences",
    "experiences.title": "Unforgettable Moments",
    "experiences.description": "From private yacht charters in Greece to wine tastings in Italy, we craft experiences that become lifelong memories.",
    "experiences.cta": "Explore All Experiences",
    
    // About Preview
    "about.tagline": "About Us",
    "about.title": "Your Journey, Our Passion",
    "about.subtitle": "Trust and Luxury Redefined",
    "about.description": "With decades of experience crafting luxury travel experiences across Greece, Italy, Poland, Austria, UAE, Sri Lanka, and the Philippines, we transform dreams into extraordinary journeys.",
    "about.cta": "Learn More About Us",
    "about.stat.destinations": "Destinations",
    "about.stat.travelers": "Happy Travelers",
    "about.stat.experiences": "Curated Experiences",
    "about.stat.support": "Support",
    "about.preview.p1": "We are twin brothers and entrepreneurs with a shared passion for travel, people, and meaningful experiences. Our journey began at a young age, when we started planning trips not as a product, but as a responsibility.",
    "about.preview.p2": "From the start, we understood that when people travel, they trust you with their time, their money, and their expectations. Over the years, we have built our approach around one clear belief: a great travel experience is created through listening, precision, and care.",
    "about.preview.p3": "We take the time to understand who is standing in front of us, what they are looking for, and what truly matters to them. Every itinerary, detail, and decision is built with intention.",
    
    // Contact Section
    "contact.tagline": "Get In Touch",
    "contact.title": "Start Your Journey",
    "contact.description": "Ready to experience the world in extraordinary style? Let our travel experts craft your perfect journey.",
    "contact.form.name": "Full Name",
    "contact.form.email": "Email Address",
    "contact.form.phone": "Phone Number",
    "contact.form.country": "Country",
    "contact.form.destination": "Destination",
    "contact.form.destination.select": "Select destination",
    "contact.form.travelers": "Number of Travelers",
    "contact.form.dates": "Preferred Travel Dates",
    "contact.form.budget": "Estimated Budget",
    "contact.form.budget.select": "Select budget range",
    "contact.form.travelerType": "Who will be traveling?",
    "contact.form.experienceType": "What type of experience are you seeking?",
    "contact.form.requests": "Additional Requests or Special Occasions",
    "contact.form.requests.placeholder": "Tell us about any special occasions, preferences, or specific experiences you'd like included...",
    "contact.form.submit": "Submit Inquiry",
    "contact.form.submitting": "Submitting...",
    "contact.form.contactInfo": "Contact Information",
    "contact.form.travelPlans": "Your Travel Plans",
    "contact.form.idealExperience": "Your Ideal Experience",
    "contact.success.title": "Thank you for your inquiry!",
    "contact.success.message": "We'll get back to you within 24-48 hours to discuss your dream journey.",
    "contact.error.title": "Submission failed",
    "contact.error.message": "Please try again or contact us directly.",
    "contact.info.email": "Email",
    "contact.info.phone": "Phone / WhatsApp",
    "contact.info.office": "Office",
    "contact.info.getInTouch": "Get In Touch",
    "contact.whiteGlove.title": "White Glove Service",
    "contact.whiteGlove.desc": "Our team is available 24/7 for your travel needs. We ensure every detail is handled with care.",
    
    // Contact Form Options - Destinations
    "contact.dest.italy": "Italy",
    "contact.dest.france": "France",
    "contact.dest.greece": "Greece",
    "contact.dest.croatia": "Croatia",
    "contact.dest.portugal": "Portugal",
    "contact.dest.spain": "Spain",
    "contact.dest.austria": "Austria",
    "contact.dest.switzerland": "Switzerland",
    "contact.dest.srilanka": "Sri Lanka",
    "contact.dest.thailand": "Thailand",
    "contact.dest.japan": "Japan",
    "contact.dest.other": "Other",
    
    // Contact Form Options - Traveler Types
    "contact.traveler.solo": "Solo Traveler",
    "contact.traveler.couple": "Couple/Partner",
    "contact.traveler.familyYoung": "Family with Young Children (under 12)",
    "contact.traveler.familyTeens": "Family with Teens (12-18)",
    "contact.traveler.multiGen": "Multi-Generational",
    "contact.traveler.friends": "Group of Friends",
    
    // Contact Form Options - Budget Ranges
    "contact.budget.5k": "$5,000 - $10,000 (Hotel/Resort Only)",
    "contact.budget.10k": "$10,000 - $20,000 (Hotel + Personalized Enhancements)",
    "contact.budget.20k": "$20,000 - $50,000 (Fully Customized Luxury Experience)",
    "contact.budget.50k": "$50,000 - $100,000 (Ultra-Luxury Journey)",
    "contact.budget.100k": "$100,000+ (Bespoke, Once-in-a-Lifetime Itinerary)",
    
    // Contact Form Options - Experience Types
    "contact.exp.hotel": "Luxury Hotel or Resort Booking",
    "contact.exp.villa": "Private Villa Rental",
    "contact.exp.cruise": "Exclusive Cruise or Yacht Charter",
    "contact.exp.safari": "Bespoke Safari or Adventure Travel",
    "contact.exp.tours": "Private Guided Tours & VIP Access",
    "contact.exp.wellness": "Wellness & Spa Retreat",
    
    // Footer
    "footer.description": "Crafting extraordinary travel experiences across the world's most captivating destinations.",
    "footer.quickLinks": "Quick Links",
    "footer.destinations": "Destinations",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.crafted": "Crafted with passion for extraordinary journeys",
    
    // Services Page
    "services.page.tagline": "What We Offer",
    "services.page.title": "Our Services",
    "services.page.description": "From the first idea until your plane lands back home, every detail is thoughtfully planned to create memories that last across Greece, Italy, Poland, Austria, UAE, Sri Lanka, and the Philippines.",
    "services.page.cta.title": "Ready to Start Your Journey?",
    "services.page.cta.desc": "Let us craft a bespoke travel experience tailored to your dreams.",
    "services.page.cta.button": "Plan Your Journey",
    "services.tailor.title": "Tailor-Made Holidays",
    "services.tailor.desc": "We design journeys that reflect your personality, rhythm, and dreams. From destination selection to itinerary planning, hotel bookings, restaurant reservations, and unique experiences across Greece, Italy, Austria, UAE, and beyond.",
    "services.tailor.f1": "Personalized itinerary design",
    "services.tailor.f2": "Handpicked accommodations",
    "services.tailor.f3": "Restaurant reservations",
    "services.tailor.f4": "Activity planning",
    "services.tailor.f5": "24/7 travel support",
    "services.boutique.title": "Boutique Journeys",
    "services.boutique.desc": "Curated experiences with meaning. We create boutique journeys to select destinations around the world, combining culture, gastronomy, wine, and adventure. Explore the vineyards of Italy, temples of Sri Lanka, or beaches of the Philippines.",
    "services.boutique.f1": "Curated group experiences",
    "services.boutique.f2": "Cultural immersion",
    "services.boutique.f3": "Gastronomy & wine tours",
    "services.boutique.f4": "Expert local guides",
    "services.boutique.f5": "Unique accommodations",
    "services.family.title": "Family & Group Operations",
    "services.family.desc": "Complete solutions for groups and families. We handle all logistics – flights, accommodations, transportation, guides – so you can simply enjoy the journey. Perfect for multi-generational trips to Poland, Austria, or island hopping in Greece.",
    "services.family.f1": "Multi-generational planning",
    "services.family.f2": "Group coordination",
    "services.family.f3": "Private transportation",
    "services.family.f4": "Kid-friendly activities",
    "services.family.f5": "Seamless logistics",
    "services.concierge.page.title": "Concierge Services",
    "services.concierge.page.desc": "Wherever you travel, we're already there. Our extensive network provides a full, personalized concierge experience in Dubai, Athens, Rome, Vienna, and all our featured destinations worldwide.",
    "services.concierge.f1": "VIP access & reservations",
    "services.concierge.f2": "Private guides & drivers",
    "services.concierge.f3": "Local recommendations",
    "services.concierge.f4": "Emergency assistance",
    "services.concierge.f5": "Special requests",
    
    // Experiences Page
    "experiences.page.tagline": "Signature Journeys",
    "experiences.page.title": "Boutique Experiences",
    "experiences.page.description": "Some journeys are stories – filled with taste, color, people, and moments that stay with you. Every boutique experience is crafted to touch the senses across our featured destinations worldwide.",
    "experiences.highlights": "Highlights",
    "experiences.inquire": "Inquire About This Experience",
    "experiences.custom.tagline": "Custom Journeys",
    "experiences.custom.title": "Looking for Something Unique?",
    "experiences.custom.desc": "Can't find exactly what you're looking for? Let us craft a bespoke experience tailored entirely to your preferences across Greece, Italy, Poland, Austria, UAE, Sri Lanka, or the Philippines.",
    "experiences.custom.button": "Design My Journey",
    "experiences.mediterranean.title": "Mediterranean Discovery",
    "experiences.mediterranean.location": "Greece & Italy",
    "experiences.mediterranean.desc": "Explore the cradle of civilization with island hopping in Greece and coastal drives along the Amalfi. From the white-washed villages of Santorini to the ancient ruins of Rome, experience Mediterranean luxury at its finest.",
    "experiences.mediterranean.duration": "10-14 Days",
    "experiences.mediterranean.h1": "Greek island hopping",
    "experiences.mediterranean.h2": "Amalfi Coast drive",
    "experiences.mediterranean.h3": "Wine tasting in Tuscany",
    "experiences.mediterranean.h4": "Private yacht experiences",
    "experiences.culinary.title": "Culinary Immersion",
    "experiences.culinary.location": "Italy & Austria",
    "experiences.culinary.desc": "Experience authentic European cuisine with local chefs in Italian countryside villas and Viennese coffee houses. Learn traditional recipes, visit local markets, and savor the finest regional delicacies.",
    "experiences.culinary.duration": "7-10 Days",
    "experiences.culinary.h1": "Cooking classes",
    "experiences.culinary.h2": "Truffle hunting in Italy",
    "experiences.culinary.h3": "Vienna coffee culture",
    "experiences.culinary.h4": "Wine estate visits",
    "experiences.wellness.title": "Wellness Retreat",
    "experiences.wellness.location": "Sri Lanka & Philippines",
    "experiences.wellness.desc": "Rejuvenate body and soul with yoga, meditation, and spa treatments in serene Asian destinations. Our wellness retreats combine ancient Ayurvedic practices with pristine island beaches for complete transformation.",
    "experiences.wellness.duration": "7-14 Days",
    "experiences.wellness.h1": "Ayurvedic spa in Sri Lanka",
    "experiences.wellness.h2": "Beach yoga in Philippines",
    "experiences.wellness.h3": "Meditation retreats",
    "experiences.wellness.h4": "Healthy cuisine",
    "experiences.alpine.title": "Alpine Adventure",
    "experiences.alpine.location": "Austria & Poland",
    "experiences.alpine.desc": "Thrilling adventures through breathtaking alpine landscapes with luxury stays. Experience the romance of the Austrian Alps, explore historic Polish cities, and discover the natural beauty of Central Europe.",
    "experiences.alpine.duration": "5-8 Days",
    "experiences.alpine.h1": "Alpine hiking & skiing",
    "experiences.alpine.h2": "Historic Krakow tours",
    "experiences.alpine.h3": "5-star mountain lodges",
    "experiences.alpine.h4": "Scenic train journeys",
    "experiences.desert.title": "Desert & Luxury",
    "experiences.desert.location": "UAE",
    "experiences.desert.desc": "Experience the ultimate in modern luxury combined with timeless desert adventures. From the iconic skyline of Dubai to serene desert camps under the stars, discover the magic of the Arabian Peninsula.",
    "experiences.desert.duration": "5-7 Days",
    "experiences.desert.h1": "Dubai luxury shopping",
    "experiences.desert.h2": "Desert safari adventures",
    "experiences.desert.h3": "Abu Dhabi culture",
    "experiences.desert.h4": "World-class dining",
    
    // Gallery Page
    "gallery.tagline": "Visual Inspiration",
    "gallery.title": "Destination Gallery",
    "gallery.description": "Explore stunning photography from our featured destinations across Greece, Italy, Poland, Austria, UAE, Sri Lanka, and the Philippines.",
    "gallery.filter.all": "All",
    "gallery.noImages": "No images found for this destination.",
    
    // About Page
    "about.page.tagline": "Our Story",
    "about.page.title": "About Us",
    "about.page.description": "We are twin brothers and entrepreneurs with a shared passion for travel, people, and meaningful experiences.",
    "about.trust.tagline": "Trust and Luxury Redefined",
    "about.trust.title": "Trust and Luxury Redefined",
    "about.trust.p1": "We are twin brothers and entrepreneurs with a shared passion for travel, people, and meaningful experiences. Our journey began at a young age, when we started planning trips not as a product, but as a responsibility.",
    "about.trust.p2": "From the start, we understood that when people travel, they trust you with their time, their money, and their expectations. Over the years, we have built our approach around one clear belief: a great travel experience is created through listening, precision, and care.",
    "about.trust.p3": "We take the time to understand who is standing in front of us, what they are looking for, and what truly matters to them. Every itinerary, detail, and decision is built with intention.",
    "about.trust.link": "Learn More About Us",
    "about.philosophy.title": "Our Philosophy",
    "about.philosophy.intro": "Over the years, we have built our approach around one clear belief: a great travel experience is created through listening, precision, and care.",
    "about.belief.listening": "Listening First",
    "about.belief.listening.desc": "We take the time to understand who is standing in front of us, what they are looking for, and what truly matters to them.",
    "about.belief.intention": "Built With Intention",
    "about.belief.intention.desc": "Every itinerary, detail, and decision is crafted with purpose. Nothing is added without reason.",
    "about.belief.involvement": "Personal Involvement",
    "about.belief.involvement.desc": "We are involved in every stage, from the first conversation to the final moments of the journey.",
    "about.belief.quality": "Quality Over Quantity",
    "about.belief.quality.desc": "Each experience is planned personally, with close attention to quality, comfort, and flow.",
    "about.belief.templates": "No Templates",
    "about.belief.templates.desc": "We do not believe in one-size-fits-all solutions. Every journey is unique.",
    "about.belief.precision": "Precision & Care",
    "about.belief.precision.desc": "A great travel experience is created through listening, precision, and genuine care.",
    "about.promise.title": "Our Promise to You",
    "about.promise.p1": "We are involved in every stage, from the first conversation to the final moments of the journey. We don't hand you off to a team or disappear after booking. We stay with you, ensuring every detail unfolds as planned.",
    "about.promise.p2": "Our commitment is to create travel experiences that feel effortless, personal, and memorable. Not because we follow a script, but because we genuinely care about the outcome.",
    "about.quote": "When our clients are happy, we are happy. That is the simplest measure of success we know.",
    "about.cta.title": "Let's Create Your Story",
    "about.cta.desc": "Ready to experience travel done differently? Get in touch and let us design a journey that's uniquely yours.",
    "about.cta.button": "Start Planning",
    
    // Personal Page
    "personal.page.tagline": "Tailored For You",
    "personal.page.title": "Personal Travel",
    "personal.page.description": "A journey that reflects your lifestyle, preferences, and expectations – without templates or predefined paths.",
    "personal.intro.title": "Igniting your spirit. Pampering your soul.",
    "personal.intro.p1": "We stand out by flawlessly delivering impeccable destinations, itineraries, accommodations, and everything in between. Our exceptional team excels in understanding your requirements, providing precise recommendations, and crafting the perfect travel plan. We possess the expertise to elevate any experience to enchanting heights.",
    "personal.intro.p2": "We understand that every dream destination should consistently deliver luxurious comfort and peace of mind, no matter where your imagination takes you.",
    "personal.intro.p3": "Partnering with us unlocks a world of extraordinary possibilities, where every journey is tailored to your unique desires. With personalized expertise and insider connections, we go beyond the ordinary to create escapes that captivate and inspire. Your next adventure awaits, and we're here to ensure it surpasses your wildest dreams.",
    "personal.quest.title": "Quest",
    "personal.quest.intro": "Whether you're seeking off-the-grid adventure in the Rockies, dreaming of a sunrise at a world's largest Buddhist temple, or simply craving a delicious beach retreat, we'll help you create memories to last a lifetime.",
    "personal.quest.beach": "Beach Escapes",
    "personal.quest.beach.desc": "Sink your toes into the soft sands of the Maldives, soak up the sun in Turks and Caicos, or unwind on the glamorous shores of the French Riviera.",
    "personal.quest.culture": "Cultural Immersions",
    "personal.quest.culture.desc": "Explore ancient temples in Kyoto, wander through the historic streets of Rome, or discover the vibrant traditions of Morocco.",
    "personal.quest.wine": "Wine Tasting",
    "personal.quest.wine.desc": "Savor the rich flavors of Tuscany, wander through the vineyards of Napa Valley, or explore the renowned wineries of Argentina's Mendoza region.",
    "personal.quest.adventure": "Adventure Expeditions",
    "personal.quest.adventure.desc": "Trek through the Patagonian wilderness, dive into the crystal waters of the Great Barrier Reef, or summit peaks in the Swiss Alps.",
    "personal.quest.wellness": "Wellness Retreats",
    "personal.quest.wellness.desc": "Rejuvenate at world-class spas in Bali, practice yoga in the Himalayas, or find serenity at thermal springs in Iceland.",
    "personal.quest.culinary": "Culinary Journeys",
    "personal.quest.culinary.desc": "Master the art of French cuisine in Paris, learn authentic Italian dishes in Florence, or explore the vibrant flavors of Thailand in Bangkok.",
    "personal.memories.title": "Creating memories that become legacies",
    "personal.memories.desc": "Travel, at its best, is an immersive authentic experience that connects travelers to history, to nature, to adventure and to each other. Whether you're celebrating a milestone anniversary, connecting as father and son while exploring the edge of the world, or experiencing Christmas in a fairytale wintry castle, we create a trip that builds these important connections.",
    "personal.occasion.romantic": "Romantic Getaways",
    "personal.occasion.honeymoon": "Honeymoons",
    "personal.occasion.milestone": "Major Milestones",
    "personal.occasion.family": "Multi-Generation Family Reunions",
    "personal.occasion.friends": "Adventures with Friends",
    "personal.occasion.solo": "Solo Journeys of Discovery",
    "personal.peace.title": "Peace of Mind, Every Step of the Way",
    "personal.peace.p1": "Travel should feel effortless. We stay connected with our global partners and monitor every detail behind the scenes so your trip unfolds smoothly from start to finish. From seamless adjustments to thoughtful guidance and on-the-ground support, our team is here to ensure your journey feels easy, secure, and completely taken care of.",
    "personal.peace.p2": "We're not just planning itineraries — we're protecting your time, elevating your experience, and giving you true peace of mind wherever you go.",
    "personal.quote": "Personal travel is for those who value quality, clarity, and a calm, well-managed experience — created entirely around them.",
    "personal.cta": "Start Planning Your Journey",
    
    // Elite Journeys Page
    "elite.page.tagline": "Premium Luxury",
    "elite.page.title": "Elite Journeys",
    "elite.page.description": "Our highest level of travel design, created for clients who expect complete personalization and absolute discretion.",
    "elite.intro.title": "Excellence without compromise. Luxury without limits.",
    "elite.intro.p1": "Premium Luxury is our highest level of travel design. It is created for clients who expect complete personalization, absolute discretion, and a journey that feels effortless from beginning to end.",
    "elite.intro.p2": "At this level, every experience is built from the ground up. There are no templates, no fixed routes, and no compromises. Each journey is designed around your preferences, pace, and vision, whether it involves private villas, exclusive resorts, remote destinations, or multi-country itineraries.",
    "elite.intro.p3": "The process begins with understanding you. We take the time to learn how you like to travel, what matters to you, and how you define comfort and luxury. From there, we carefully design an experience that feels natural, balanced, and precise.",
    "elite.experience.title": "The Elite Experience",
    "elite.experience.intro": "Premium Luxury is defined by how everything flows. Private aviation, VIP arrivals, seamless transfers, handpicked accommodations, and exclusive access are coordinated with accuracy and calm.",
    "elite.feature.aviation": "Private Aviation",
    "elite.feature.aviation.desc": "Seamless private jet arrangements, VIP airport handling, and direct transfers to your destination without delays or crowds.",
    "elite.feature.accommodations": "Exclusive Accommodations",
    "elite.feature.accommodations.desc": "Handpicked private villas, luxury suites, and exclusive resorts that offer unparalleled privacy and service.",
    "elite.feature.concierge": "Personal Concierge",
    "elite.feature.concierge.desc": "Dedicated support available 24/7, managing every request with precision and discretion throughout your journey.",
    "elite.feature.experiences": "Curated Experiences",
    "elite.feature.experiences.desc": "Access to exclusive events, private viewings, after-hours museum tours, and experiences unavailable to the public.",
    "elite.feature.security": "Security & Privacy",
    "elite.feature.security.desc": "Comprehensive security arrangements, confidential travel planning, and complete discretion at every stage.",
    "elite.feature.logistics": "Seamless Logistics",
    "elite.feature.logistics.desc": "Every transfer, reservation, and timing coordinated with military precision for a flawless experience.",
    "elite.pillars.title": "The pillars of elite travel",
    "elite.pillars.intro": "This is not travel built around destinations alone. It is travel shaped by atmosphere, comfort, and trust. Every moment is intentional, every choice considered, and every experience designed to feel uniquely yours.",
    "elite.pillar.personalization": "Complete Personalization",
    "elite.pillar.discretion": "Absolute Discretion",
    "elite.pillar.execution": "Effortless Execution",
    "elite.pillar.quality": "Uncompromising Quality",
    "elite.pillar.support": "24/7 Dedicated Support",
    "elite.pillar.access": "World-Class Access",
    "elite.confidence.title": "Confidence at Every Step",
    "elite.confidence.p1": "The service is personal and available at all times. Clients receive dedicated support before, during, and after the journey, with full attention to timing, privacy, and individual needs. Discretion and reliability are never optional.",
    "elite.confidence.p2": "Our team manages every detail behind the scenes, allowing you to focus only on the experience itself. From the first conversation to the final moments of your journey, everything is handled with precision and care.",
    "elite.quote": "Premium Luxury is about confidence. Knowing that everything is handled properly, quietly, and to the highest standard.",
    "elite.cta": "Design Your Elite Journey",
    
    // Private Flights Page
    "flights.page.tagline": "Private Aviation",
    "flights.page.title": "Private Flights",
    "flights.page.description": "Professional, around-the-clock assistance in arranging private flights, tailored precisely to each client.",
    "flights.intro.title": "Time is precious. Travel should be seamless.",
    "flights.intro.p1": "Private flights are designed for clients who value time, privacy, and complete reliability. As part of our services, we provide professional, around-the-clock assistance in arranging private flights, tailored precisely to each client.",
    "flights.intro.p2": "We work with trusted aviation partners and carefully selected operators, allowing us to offer access to a wide range of private aircraft for both short and long distance flights. Every detail is managed to ensure your journey is smooth, comfortable, and precisely on schedule.",
    "flights.service.title": "Full Service",
    "flights.service.intro": "From the first inquiry, we manage the entire process. Every aspect of your private flight is handled with care and clarity, allowing the experience to remain calm and seamless.",
    "flights.service.aircraft": "Aircraft Selection",
    "flights.service.aircraft.desc": "Access to a wide range of private aircraft for short and long-distance flights, matched to your specific needs.",
    "flights.service.scheduling": "Flight Scheduling",
    "flights.service.scheduling.desc": "Flexible departure times that work around your schedule, not the other way around.",
    "flights.service.routing": "Route Planning",
    "flights.service.routing.desc": "Optimized routing for efficiency, comfort, and minimal travel time.",
    "flights.service.ground": "Ground Handling",
    "flights.service.ground.desc": "VIP arrivals and departures, private terminals, and seamless ground coordination.",
    "flights.service.special": "Special Requests",
    "flights.service.special.desc": "Catering, in-flight amenities, and personalized touches handled with precision.",
    "flights.service.security": "Security Arrangements",
    "flights.service.security.desc": "Complete discretion and security coordination when required.",
    "flights.commitment.title": "Our commitment to you",
    "flights.commitment.p1": "Every flight is planned with strict attention to safety, comfort, discretion, and timing. Time is a critical factor in private aviation. We place strong emphasis on punctuality, clear coordination, and precise execution.",
    "flights.commitment.p2": "Our service is available 24/7. Clients receive continuous support before, during, and after the flight, with a direct and responsive point of contact at all times.",
    "flights.commitment.247": "24/7 Availability",
    "flights.commitment.contact": "Direct Point of Contact",
    "flights.commitment.punctuality": "Strict Punctuality",
    "flights.commitment.discretion": "Complete Discretion",
    "flights.commitment.partners": "Trusted Aviation Partners",
    "flights.commitment.coordination": "Seamless Coordination",
    "flights.beyond.title": "Beyond Luxury",
    "flights.beyond.p1": "Private aviation is not only about luxury. It is about efficiency, trust, and confidence in the people managing your journey. Our role is to make sure every flight is handled professionally and on time.",
    "flights.beyond.p2": "From departure to arrival, every detail is managed to ensure the flight operates exactly as planned. Your time matters, and we treat it with the respect it deserves.",
    "flights.quote": "Efficiency, trust, and confidence – the foundations of every flight we arrange.",
    "flights.cta": "Inquire About Private Flights",
    
    // Boutique Page
    "boutique.page.tagline": "Curated Experiences",
    "boutique.page.title": "Boutique Experience",
    "boutique.page.description": "Handcrafted journeys featuring desert luxury, alpine adventures, Mediterranean discovery, and culinary immersion.",
    "boutique.intro.title": "Journeys crafted with intention and care.",
    "boutique.intro.p1": "Our boutique experiences are not mass-produced itineraries. Each journey is carefully designed to offer depth, authenticity, and a connection to the destination that goes beyond the surface.",
    "boutique.intro.p2": "From the stillness of the Arabian desert to the winding roads of the Alps, from the flavors of Greece to the rolling hills of Tuscany – every experience is built around quality, precision, and your personal preferences.",
    "boutique.uae.title": "UAE Desert Luxury",
    "boutique.uae.subtitle": "Modern Elegance Meets Desert Stillness",
    "boutique.uae.intro": "The UAE offers a refined blend of modern elegance and the timeless stillness of the desert. This experience is designed for travelers who expect precision, discretion, and a fully managed journey from start to finish.",
    "boutique.uae.content": "From the moment you arrive, every detail is taken care of. Private transfers, VIP airport handling, and seamless coordination ensure a smooth and calm beginning. The journey continues beyond the city, with the option of a private helicopter transfer directly into the desert. Guests arrive discreetly at Al Maha Desert Resort & Spa, a secluded sanctuary set deep within the dunes. Private villas with personal pools, expansive desert views, and complete privacy create an atmosphere of quiet luxury.",
    "boutique.uae.closing": "This experience is not only about luxury. It is about peace of mind, privacy, and knowing that everything is managed with care, accuracy, and respect for your time.",
    "boutique.uae.h1": "Private helicopter transfer to desert sanctuary",
    "boutique.uae.h2": "Private villas with personal pools",
    "boutique.uae.h3": "24/7 personal assistance and security",
    "boutique.uae.h4": "VIP airport handling and transfers",
    "boutique.uae.h5": "Complete privacy and discretion",
    "boutique.alpine.title": "Alpine Adventure",
    "boutique.alpine.subtitle": "Austria & Italy Driving Experience",
    "boutique.alpine.intro": "This experience is designed for those who appreciate performance, scenery, and absolute freedom of movement. A private alpine journey through Austria and Italy, combining iconic mountain roads with high-performance motor cars.",
    "boutique.alpine.content": "Each journey is custom built. Routes, driving pace, destinations, and experiences are planned according to personal preferences. The Alps offer some of the most impressive driving roads in Europe. Winding mountain passes, open stretches, dramatic views, and quiet valleys create a driving experience that feels powerful and refined. Premium vehicles, logistics, accommodations, dining, and daily coordination are fully managed.",
    "boutique.alpine.closing": "This is not a standard car tour. It is a carefully curated alpine journey, built around quality, precision, and enjoyment – a combination of driving, scenery, service, and trust.",
    "boutique.alpine.h1": "High-performance premium vehicles",
    "boutique.alpine.h2": "Iconic mountain passes and scenic routes",
    "boutique.alpine.h3": "Luxury alpine lodges and hotels",
    "boutique.alpine.h4": "Fully managed logistics and coordination",
    "boutique.alpine.h5": "Custom-built itineraries",
    "boutique.mediterranean.title": "Mediterranean Discovery",
    "boutique.mediterranean.subtitle": "Greece Through Taste and Elegance",
    "boutique.mediterranean.intro": "Mediterranean Discovery is an invitation to experience Greece through taste, elegance, and quiet luxury. This journey blends authentic local flavors with refined hospitality, designed for travelers who value depth, comfort, and thoughtful details.",
    "boutique.mediterranean.content": "The experience begins with arrival at a private airport in Northern Greece, ensuring privacy and a smooth transition. In the following days, the region opens gradually. Private visits to local wineries, authentic olive oil estates, and carefully chosen culinary stops create a deep connection to the land. Chef-curated meals highlight local ingredients, seasonal flavors, and Mediterranean simplicity at its finest.",
    "boutique.mediterranean.closing": "This is not just a trip through Greece. It is a refined Mediterranean journey, built around taste, trust, and uncompromising standards.",
    "boutique.mediterranean.h1": "Private airport arrival in Northern Greece",
    "boutique.mediterranean.h2": "Boutique hotel accommodations",
    "boutique.mediterranean.h3": "Private winery and olive estate visits",
    "boutique.mediterranean.h4": "Chef-curated seasonal meals",
    "boutique.mediterranean.h5": "Hidden locations and exclusive encounters",
    "boutique.tuscany.title": "Culinary Immersion",
    "boutique.tuscany.subtitle": "Tuscany's Authentic Flavors",
    "boutique.tuscany.intro": "Tuscany is the essence of Italian culinary tradition. This experience offers an intimate journey through Tuscany, where food, landscape, and culture come together in perfect balance.",
    "boutique.tuscany.content": "Guests stay in carefully selected boutique hotels and countryside estates, surrounded by rolling hills, vineyards, and olive groves. The experience is built around taste and authenticity. Private cooking sessions, visits to family-owned wineries, olive oil producers, and artisan workshops offer a behind-the-scenes look into Tuscan culinary heritage. Wine tastings, truffle hunting, and long, unhurried meals form the rhythm of the journey.",
    "boutique.tuscany.closing": "Culinary Immersion in Tuscany is not about excess. It is about quality, depth, and understanding Italy through its flavors, landscapes, and people.",
    "boutique.tuscany.h1": "Boutique hotels and countryside estates",
    "boutique.tuscany.h2": "Private cooking sessions with local chefs",
    "boutique.tuscany.h3": "Family-owned winery visits",
    "boutique.tuscany.h4": "Truffle hunting experiences",
    "boutique.tuscany.h5": "Artisan workshop discoveries",
    "boutique.quote": "Every boutique experience is a promise – of quality, authenticity, and moments that stay with you long after the journey ends.",
    "boutique.cta": "Craft Your Boutique Experience",
    
    // Contact Page
    "contact.page.tagline": "Start Your Journey",
    "contact.page.title": "Contact Us",
    "contact.page.description": "We're here to design your next journey with precision, care, and a personal touch. Whether you dream of Greek islands, Italian villas, or Asian retreats – share a few details to help us tailor your experience.",
  },
  he: {
    // Navigation
    "nav.home": "בית",
    "nav.services": "שירותים",
    "nav.experiences": "חוויות",
    "nav.gallery": "גלריה",
    "nav.about": "אודות",
    "nav.contact": "צור קשר",
    "nav.personal": "אישי",
    "nav.eliteJourneys": "מסעות עילית",
    "nav.privateFlights": "טיסות פרטיות",
    "nav.boutique": "בוטיק",
    "nav.requestQuote": "בקש הצעת מחיר",
    
    // Hero Section
    "hero.tagline": "חוויות נסיעה יוקרתיות",
    "hero.discover": "גלה את",
    "hero.description": "השותף שלך לנסיעות ברחבי העולם – יוצרים מסעות בלתי נשכחים ביעדים הנבחרים שלנו.",
    "hero.cta.plan": "תכנן את המסע שלך",
    "hero.cta.explore": "גלה חוויות",
    "hero.cta.story": "גלה את הסיפור שלנו",
    "hero.scroll": "גלול",
    
    // Hero Slides
    "hero.slide1.headline": "מטיילים מנוסים",
    "hero.slide1.subheadline": "חווה את אמנות הפינוק",
    "hero.slide1.description": "יועצי הנסיעות היוקרתיות שלנו מספקים חוויות פינוק יוצאות דופן בכל מקום שהחיים לוקחים אותך.",
    "hero.slide2.headline": "לה דולצ'ה ויטה",
    "hero.slide2.subheadline": "טוסקנה מחכה לך",
    "hero.slide2.description": "טעם את הטעמים העשירים של טוסקנה, מכרמים ברמה עולמית ועד חוויות קולינריות אותנטיות.",
    "hero.slide3.headline": "מצוינות אלפינית",
    "hero.slide3.subheadline": "כאשר ביצועים פוגשים נוף",
    "hero.slide3.description": "מסעות אלפיניים פרטיים דרך אוסטריה ואיטליה, משלבים כבישי הרים אייקוניים עם יוקרה.",
    "hero.slide4.headline": "שלווה מדברית",
    "hero.slide4.subheadline": "אלגנטיות מודרנית פוגשת דממה נצחית",
    "hero.slide4.description": "חווה את השילוב המעודן של יוקרה מודרנית ויופי רגוע של המדבר.",
    "hero.slide5.headline": "גן עדן טרופי",
    "hero.slide5.subheadline": "מים צלולים מחכים",
    "hero.slide5.description": "גלה חופים בתוליים והכנסת אורחים חמה ברחבי הארכיפלג הפיליפיני.",
    
    // Stats Section
    "stats.years": "שנות ניסיון",
    "stats.destinations": "יעדים ברחבי העולם",
    "stats.travelers": "נוסעים מרוצים",
    "stats.satisfaction": "שביעות רצון לקוחות",
    "stats.valuesTagline": "מה שאנחנו מייצגים",
    "stats.valuesTitle": "הערכים שלנו",
    "stats.passion": "תשוקה",
    "stats.passion.desc": "אנחנו אוהבים את מה שאנחנו עושים וזה ניכר בכל מסע שאנחנו יוצרים.",
    "stats.excellence": "מצוינות",
    "stats.excellence.desc": "איכות ללא פשרות בכל פרט, בכל יעד.",
    "stats.trust": "אמון",
    "stats.trust.desc": "הבטיחות והסיפוק שלך הם העדיפות הגבוהה ביותר שלנו.",
    "stats.exclusivity": "בלעדיות",
    "stats.exclusivity.desc": "גישה לחוויות ייחודיות שלא תמצא בשום מקום אחר.",
    
    // Destinations
    "dest.greece": "יוון",
    "dest.greece.tagline": "איפה המיתוסים מתעוררים לחיים",
    "dest.italy": "איטליה",
    "dest.italy.tagline": "החיים המתוקים מחכים",
    "dest.poland": "פולין",
    "dest.poland.tagline": "קסם היסטורי נחשף",
    "dest.austria": "אוסטריה",
    "dest.austria.tagline": "אלגנטיות אלפינית",
    "dest.uae": "איחוד האמירויות",
    "dest.uae.tagline": "יוקרה מודרנית מחודשת",
    "dest.srilanka": "סרי לנקה",
    "dest.srilanka.tagline": "אי הפלאות",
    "dest.philippines": "הפיליפינים",
    "dest.philippines.tagline": "גן עדן טרופי",
    "dest.worldwide": "ברחבי העולם",
    "dest.worldwide.tagline": "הרפתקאות גלובליות",
    
    // Destinations Showcase
    "destinations.tagline": "היעדים שלנו",
    "destinations.title": "גלה את העולם שלנו",
    "destinations.highlights": "נקודות עניין",
    "destinations.greece.desc": "חורבות עתיקות, איים מוזהבים וקסם ים תיכוני מחכים במולדת התרבות המערבית.",
    "destinations.greece.h1": "שקיעות סנטוריני",
    "destinations.greece.h2": "היסטוריה אתונאית",
    "destinations.greece.h3": "שייט בין איים",
    "destinations.italy.desc": "מאמנות הרנסנס ועד הזוהר החופי, חווה את החיים המתוקים בכל פינה של יעד נצחי זה.",
    "destinations.italy.h1": "חוף אמאלפי",
    "destinations.italy.h2": "כרמי טוסקנה",
    "destinations.italy.h3": "מורשת רומית",
    "destinations.poland.desc": "גלה ערים מימי הביניים, טבע בתולי והכנסת אורחים חמה בלב מרכז אירופה.",
    "destinations.poland.h1": "העיר העתיקה קראקוב",
    "destinations.poland.h2": "נופשי הרים",
    "destinations.poland.h3": "אוצרות תרבותיים",
    "destinations.austria.desc": "פאר אלפיני פוגש אלגנטיות קיסרית בסימפוניה זו של טבע ותרבות מעודנת.",
    "destinations.austria.h1": "ארמונות וינה",
    "destinations.austria.h2": "סקי אלפיני",
    "destinations.austria.h3": "מורשת מוזיקלית",
    "destinations.uae.desc": "כאשר מסורות עתיקות פוגשות יוקרה עתידנית ביעד השאפתני בעולם.",
    "destinations.uae.h1": "קו הרקיע של דובאי",
    "destinations.uae.h2": "הרפתקאות מדבר",
    "destinations.uae.h3": "קניות ברמה עולמית",
    "destinations.srilanka.desc": "חופים טרופיים, מקדשים עתיקים ומפגשי חיות בר באי הגן עדן הזה.",
    "destinations.srilanka.h1": "מטעי תה",
    "destinations.srilanka.h2": "ספארי חיות בר",
    "destinations.srilanka.h3": "מקדשים עתיקים",
    "destinations.philippines.desc": "מים צלולים, חופים בתוליים והכנסת אורחים פיליפינית חמה ב-7,000 איים.",
    "destinations.philippines.h1": "איי פלאוואן",
    "destinations.philippines.h2": "גן עדן לצוללים",
    "destinations.philippines.h3": "אתרי נופש חוף",
    "destinations.worldwide.desc": "מעבר ליעדים המובילים שלנו, אנו יוצרים מסעות מותאמים אישית לכל פינה בעולם.",
    "destinations.worldwide.h1": "מסלולים מותאמים",
    "destinations.worldwide.h2": "סיורים קבוצתיים",
    "destinations.worldwide.h3": "בריחות יוקרתיות",
    
    // Services Preview
    "services.tagline": "השירותים שלנו",
    "services.title": "שירותי נסיעות יוצאי דופן",
    "services.description": "ממסלולים מותאמים אישית ועד גישה בלעדית, אנו מטפלים בכל פרט במסע היוקרתי שלך.",
    "services.cta": "צפה בכל השירותים",
    "services.custom.title": "מסלולים מותאמים",
    "services.custom.desc": "תוכניות נסיעה מותאמות להעדפותיך",
    "services.concierge.title": "קונסיירז' 24/7",
    "services.concierge.desc": "תמיכה מסביב לשעון לאורך כל המסע",
    "services.access.title": "גישה בלעדית",
    "services.access.desc": "חוויות VIP וסיורים פרטיים",
    "services.accommodations.title": "לינה יוקרתית",
    "services.accommodations.desc": "מלונות נבחרים בקפידה ווילות פרטיות",
    
    // Experiences Preview
    "experiences.tagline": "חוויות נבחרות",
    "experiences.title": "רגעות בלתי נשכחים",
    "experiences.description": "משייט יאכטות פרטי ביוון ועד טעימות יין באיטליה, אנו יוצרים חוויות שהופכות לזכרונות לכל החיים.",
    "experiences.cta": "גלה את כל החוויות",
    
    // About Preview
    "about.tagline": "אודותינו",
    "about.title": "המסע שלך, התשוקה שלנו",
    "about.subtitle": "אמון ויוקרה מחדש",
    "about.description": "עם עשרות שנים של ניסיון ביצירת חוויות נסיעה יוקרתיות ביוון, איטליה, פולין, אוסטריה, איחוד האמירויות, סרי לנקה והפיליפינים, אנו הופכים חלומות למסעות יוצאי דופן.",
    "about.cta": "למד עוד עלינו",
    "about.stat.destinations": "יעדים",
    "about.stat.travelers": "נוסעים מרוצים",
    "about.stat.experiences": "חוויות נבחרות",
    "about.stat.support": "תמיכה",
    "about.preview.p1": "אנחנו אחים תאומים ויזמים עם תשוקה משותפת לנסיעות, אנשים וחוויות משמעותיות. המסע שלנו התחיל בגיל צעיר, כשהתחלנו לתכנן טיולים לא כמוצר, אלא כאחריות.",
    "about.preview.p2": "מההתחלה, הבנו שכאשר אנשים נוסעים, הם סומכים עליך עם הזמן שלהם, הכסף שלהם והציפיות שלהם. במהלך השנים, בנינו את הגישה שלנו סביב אמונה ברורה אחת: חוויית נסיעה נהדרת נוצרת דרך הקשבה, דיוק ואכפתיות.",
    "about.preview.p3": "אנחנו לוקחים את הזמן להבין מי עומד מולנו, מה הם מחפשים ומה באמת חשוב להם. כל מסלול, פרט והחלטה נבנים עם כוונה.",
    
    // Contact Section
    "contact.tagline": "צור קשר",
    "contact.title": "התחל את המסע שלך",
    "contact.description": "מוכן לחוות את העולם בסגנון יוצא דופן? תן למומחי הנסיעות שלנו ליצור את המסע המושלם שלך.",
    "contact.form.name": "שם מלא",
    "contact.form.email": "כתובת אימייל",
    "contact.form.phone": "מספר טלפון",
    "contact.form.country": "מדינה",
    "contact.form.destination": "יעד",
    "contact.form.destination.select": "בחר יעד",
    "contact.form.travelers": "מספר נוסעים",
    "contact.form.dates": "תאריכי נסיעה מועדפים",
    "contact.form.budget": "תקציב משוער",
    "contact.form.budget.select": "בחר טווח תקציב",
    "contact.form.travelerType": "מי יטייל?",
    "contact.form.experienceType": "איזה סוג חוויה אתה מחפש?",
    "contact.form.requests": "בקשות נוספות או אירועים מיוחדים",
    "contact.form.requests.placeholder": "ספר לנו על אירועים מיוחדים, העדפות או חוויות ספציפיות שתרצה לכלול...",
    "contact.form.submit": "שלח פנייה",
    "contact.form.submitting": "שולח...",
    "contact.form.contactInfo": "פרטי התקשרות",
    "contact.form.travelPlans": "תוכניות הנסיעה שלך",
    "contact.form.idealExperience": "החוויה האידיאלית שלך",
    "contact.success.title": "תודה על הפנייה!",
    "contact.success.message": "נחזור אליך תוך 24-48 שעות לדון במסע החלומות שלך.",
    "contact.error.title": "השליחה נכשלה",
    "contact.error.message": "אנא נסה שוב או צור איתנו קשר ישירות.",
    "contact.info.email": "אימייל",
    "contact.info.phone": "טלפון / WhatsApp",
    "contact.info.office": "משרד",
    "contact.info.getInTouch": "צור קשר",
    "contact.whiteGlove.title": "שירות White Glove",
    "contact.whiteGlove.desc": "הצוות שלנו זמין 24/7 לצרכי הנסיעה שלך. אנו מוודאים שכל פרט מטופל בזהירות.",
    
    // Contact Form Options - Destinations
    "contact.dest.italy": "איטליה",
    "contact.dest.france": "צרפת",
    "contact.dest.greece": "יוון",
    "contact.dest.croatia": "קרואטיה",
    "contact.dest.portugal": "פורטוגל",
    "contact.dest.spain": "ספרד",
    "contact.dest.austria": "אוסטריה",
    "contact.dest.switzerland": "שווייץ",
    "contact.dest.srilanka": "סרי לנקה",
    "contact.dest.thailand": "תאילנד",
    "contact.dest.japan": "יפן",
    "contact.dest.other": "אחר",
    
    // Contact Form Options - Traveler Types
    "contact.traveler.solo": "נוסע יחיד",
    "contact.traveler.couple": "זוג/בן זוג",
    "contact.traveler.familyYoung": "משפחה עם ילדים קטנים (מתחת ל-12)",
    "contact.traveler.familyTeens": "משפחה עם מתבגרים (12-18)",
    "contact.traveler.multiGen": "רב-דורי",
    "contact.traveler.friends": "קבוצת חברים",
    
    // Contact Form Options - Budget Ranges
    "contact.budget.5k": "$5,000 - $10,000 (מלון/אתר נופש בלבד)",
    "contact.budget.10k": "$10,000 - $20,000 (מלון + שיפורים מותאמים אישית)",
    "contact.budget.20k": "$20,000 - $50,000 (חוויית יוקרה מותאמת במלואה)",
    "contact.budget.50k": "$50,000 - $100,000 (מסע אולטרה-יוקרתי)",
    "contact.budget.100k": "$100,000+ (מסלול בוטיק, חוויה של פעם בחיים)",
    
    // Contact Form Options - Experience Types
    "contact.exp.hotel": "הזמנת מלון או אתר נופש יוקרתי",
    "contact.exp.villa": "השכרת וילה פרטית",
    "contact.exp.cruise": "שייט בלעדי או השכרת יאכטה",
    "contact.exp.safari": "ספארי או טיול הרפתקאות בוטיק",
    "contact.exp.tours": "סיורים מודרכים פרטיים וגישת VIP",
    "contact.exp.wellness": "נופש ספא ובריאות",
    
    // Footer
    "footer.description": "יוצרים חוויות נסיעה יוצאות דופן ביעדים המרתקים ביותר בעולם.",
    "footer.quickLinks": "קישורים מהירים",
    "footer.destinations": "יעדים",
    "footer.contact": "צור קשר",
    "footer.rights": "כל הזכויות שמורות.",
    "footer.crafted": "נוצר עם תשוקה למסעות יוצאי דופן",
    
    // Services Page
    "services.page.tagline": "מה אנחנו מציעים",
    "services.page.title": "השירותים שלנו",
    "services.page.description": "מהרעיון הראשון ועד שהמטוס שלך נוחת בחזרה הביתה, כל פרט מתוכנן בקפידה ליצור זכרונות שנשארים ביוון, איטליה, פולין, אוסטריה, איחוד האמירויות, סרי לנקה והפיליפינים.",
    "services.page.cta.title": "מוכן להתחיל את המסע שלך?",
    "services.page.cta.desc": "תן לנו ליצור חוויית נסיעה מותאמת אישית לחלומות שלך.",
    "services.page.cta.button": "תכנן את המסע שלך",
    "services.tailor.title": "חופשות מותאמות אישית",
    "services.tailor.desc": "אנו מעצבים מסעות שמשקפים את האישיות, הקצב והחלומות שלך. מבחירת יעד ועד תכנון מסלול, הזמנת מלונות, הזמנות מסעדות וחוויות ייחודיות ביוון, איטליה, אוסטריה, איחוד האמירויות ומעבר.",
    "services.tailor.f1": "עיצוב מסלול מותאם אישית",
    "services.tailor.f2": "לינה נבחרת בקפידה",
    "services.tailor.f3": "הזמנות מסעדות",
    "services.tailor.f4": "תכנון פעילויות",
    "services.tailor.f5": "תמיכה בנסיעות 24/7",
    "services.boutique.title": "מסעות בוטיק",
    "services.boutique.desc": "חוויות מובחרות עם משמעות. אנו יוצרים מסעות בוטיק ליעדים נבחרים ברחבי העולם, המשלבים תרבות, גסטרונומיה, יין והרפתקאות. גלה את כרמי איטליה, מקדשי סרי לנקה או חופי הפיליפינים.",
    "services.boutique.f1": "חוויות קבוצתיות מובחרות",
    "services.boutique.f2": "טבילה תרבותית",
    "services.boutique.f3": "סיורי גסטרונומיה ויין",
    "services.boutique.f4": "מדריכים מקומיים מומחים",
    "services.boutique.f5": "לינה ייחודית",
    "services.family.title": "פעולות משפחה וקבוצה",
    "services.family.desc": "פתרונות מלאים לקבוצות ומשפחות. אנו מטפלים בכל הלוגיסטיקה – טיסות, לינה, תחבורה, מדריכים – כך שתוכל פשוט ליהנות מהמסע. מושלם לטיולים רב-דוריים לפולין, אוסטריה או שייט בין איים ביוון.",
    "services.family.f1": "תכנון רב-דורי",
    "services.family.f2": "תיאום קבוצות",
    "services.family.f3": "תחבורה פרטית",
    "services.family.f4": "פעילויות ידידותיות לילדים",
    "services.family.f5": "לוגיסטיקה חלקה",
    "services.concierge.page.title": "שירותי קונסיירז'",
    "services.concierge.page.desc": "לאן שלא תיסע, אנחנו כבר שם. הרשת הנרחבת שלנו מספקת חוויית קונסיירז' מלאה ומותאמת אישית בדובאי, אתונה, רומא, וינה ובכל היעדים המובילים שלנו ברחבי העולם.",
    "services.concierge.f1": "גישה VIP והזמנות",
    "services.concierge.f2": "מדריכים ונהגים פרטיים",
    "services.concierge.f3": "המלצות מקומיות",
    "services.concierge.f4": "סיוע חירום",
    "services.concierge.f5": "בקשות מיוחדות",
    
    // Experiences Page
    "experiences.page.tagline": "מסעות ייחודיים",
    "experiences.page.title": "חוויות בוטיק",
    "experiences.page.description": "חלק מהמסעות הם סיפורים – מלאים בטעם, צבע, אנשים ורגעים שנשארים איתך. כל חוויית בוטיק נוצרת לגעת בחושים ביעדים המובילים שלנו ברחבי העולם.",
    "experiences.highlights": "דגשים",
    "experiences.inquire": "בירור על חוויה זו",
    "experiences.custom.tagline": "מסעות מותאמים",
    "experiences.custom.title": "מחפש משהו ייחודי?",
    "experiences.custom.desc": "לא מצאת בדיוק את מה שאתה מחפש? תן לנו ליצור חוויה מותאמת אישית לחלוטין להעדפות שלך ביוון, איטליה, פולין, אוסטריה, איחוד האמירויות, סרי לנקה או הפיליפינים.",
    "experiences.custom.button": "עצב את המסע שלי",
    "experiences.mediterranean.title": "גילוי ים תיכוני",
    "experiences.mediterranean.location": "יוון ואיטליה",
    "experiences.mediterranean.desc": "גלה את ערש התרבות עם שייט בין איים ביוון ונסיעות חוף לאורך אמאלפי. מהכפרים הלבנים של סנטוריני ועד החורבות העתיקות של רומא, חווה יוקרה ים תיכונית במיטבה.",
    "experiences.mediterranean.duration": "10-14 ימים",
    "experiences.mediterranean.h1": "שייט בין איים יווניים",
    "experiences.mediterranean.h2": "נסיעה בחוף אמאלפי",
    "experiences.mediterranean.h3": "טעימות יין בטוסקנה",
    "experiences.mediterranean.h4": "חוויות יאכטה פרטיות",
    "experiences.culinary.title": "טבילה קולינרית",
    "experiences.culinary.location": "איטליה ואוסטריה",
    "experiences.culinary.desc": "חווה מטבח אירופי אותנטי עם שפים מקומיים בווילות בכפר האיטלקי ובבתי הקפה הווינאיים. למד מתכונים מסורתיים, בקר בשווקים מקומיים וטעם את המעדנים האזוריים המשובחים ביותר.",
    "experiences.culinary.duration": "7-10 ימים",
    "experiences.culinary.h1": "שיעורי בישול",
    "experiences.culinary.h2": "ציד כמהין באיטליה",
    "experiences.culinary.h3": "תרבות הקפה הווינאית",
    "experiences.culinary.h4": "ביקורים ביקבים",
    "experiences.wellness.title": "נסיגת בריאות",
    "experiences.wellness.location": "סרי לנקה והפיליפינים",
    "experiences.wellness.desc": "התחדש בגוף ובנפש עם יוגה, מדיטציה וטיפולי ספא ביעדים אסייתיים שלווים. נסיגות הבריאות שלנו משלבות שיטות איורוודיות עתיקות עם חופי איים בתוליים לשינוי מוחלט.",
    "experiences.wellness.duration": "7-14 ימים",
    "experiences.wellness.h1": "ספא איורוודי בסרי לנקה",
    "experiences.wellness.h2": "יוגה בחוף בפיליפינים",
    "experiences.wellness.h3": "נסיגות מדיטציה",
    "experiences.wellness.h4": "מטבח בריאות",
    "experiences.alpine.title": "הרפתקה אלפינית",
    "experiences.alpine.location": "אוסטריה ופולין",
    "experiences.alpine.desc": "הרפתקאות מרגשות דרך נופים אלפיניים עוצרי נשימה עם שהייה יוקרתית. חווה את הרומנטיקה של האלפים האוסטריים, גלה ערים היסטוריות פולניות וגלה את היופי הטבעי של מרכז אירופה.",
    "experiences.alpine.duration": "5-8 ימים",
    "experiences.alpine.h1": "טיולים וסקי אלפיני",
    "experiences.alpine.h2": "סיורים בקרקוב ההיסטורית",
    "experiences.alpine.h3": "לודג'ים הרריים 5 כוכבים",
    "experiences.alpine.h4": "מסעות רכבת נופיים",
    "experiences.desert.title": "מדבר ויוקרה",
    "experiences.desert.location": "איחוד האמירויות",
    "experiences.desert.desc": "חווה את השיא של יוקרה מודרנית משולבת עם הרפתקאות מדבר נצחיות. מקו הרקיע האייקוני של דובאי ועד מחנות מדבר שלווים מתחת לכוכבים, גלה את הקסם של חצי האי הערבי.",
    "experiences.desert.duration": "5-7 ימים",
    "experiences.desert.h1": "קניות יוקרה בדובאי",
    "experiences.desert.h2": "הרפתקאות ספארי מדבר",
    "experiences.desert.h3": "תרבות אבו דאבי",
    "experiences.desert.h4": "אוכל ברמה עולמית",
    
    // Gallery Page
    "gallery.tagline": "השראה ויזואלית",
    "gallery.title": "גלריית יעדים",
    "gallery.description": "גלה צילומים מדהימים מהיעדים המובילים שלנו ביוון, איטליה, פולין, אוסטריה, איחוד האמירויות, סרי לנקה והפיליפינים.",
    "gallery.filter.all": "הכל",
    "gallery.noImages": "לא נמצאו תמונות ליעד זה.",
    
    // About Page
    "about.page.tagline": "הסיפור שלנו",
    "about.page.title": "אודותינו",
    "about.page.description": "אנחנו אחים תאומים ויזמים עם תשוקה משותפת לנסיעות, אנשים וחוויות משמעותיות.",
    "about.trust.tagline": "אמון ויוקרה מוגדרים מחדש",
    "about.trust.title": "אמון ויוקרה מוגדרים מחדש",
    "about.trust.p1": "אנחנו אחים תאומים ויזמים עם תשוקה משותפת לנסיעות, אנשים וחוויות משמעותיות. המסע שלנו התחיל בגיל צעיר, כשהתחלנו לתכנן טיולים לא כמוצר, אלא כאחריות.",
    "about.trust.p2": "מההתחלה, הבנו שכאשר אנשים נוסעים, הם סומכים עליך עם הזמן שלהם, הכסף שלהם והציפיות שלהם. במהלך השנים, בנינו את הגישה שלנו סביב אמונה ברורה אחת: חוויית נסיעה נהדרת נוצרת דרך הקשבה, דיוק ואכפתיות.",
    "about.trust.p3": "אנחנו לוקחים את הזמן להבין מי עומד מולנו, מה הם מחפשים ומה באמת חשוב להם. כל מסלול, פרט והחלטה נבנים בכוונה.",
    "about.trust.link": "למד עוד עלינו",
    "about.philosophy.title": "הפילוסופיה שלנו",
    "about.philosophy.intro": "במהלך השנים, בנינו את הגישה שלנו סביב אמונה ברורה אחת: חוויית נסיעה נהדרת נוצרת דרך הקשבה, דיוק ואכפתיות.",
    "about.belief.listening": "הקשבה ראשונה",
    "about.belief.listening.desc": "אנחנו לוקחים את הזמן להבין מי עומד מולנו, מה הם מחפשים ומה באמת חשוב להם.",
    "about.belief.intention": "בנוי עם כוונה",
    "about.belief.intention.desc": "כל מסלול, פרט והחלטה נוצרים במטרה. שום דבר לא נוסף ללא סיבה.",
    "about.belief.involvement": "מעורבות אישית",
    "about.belief.involvement.desc": "אנחנו מעורבים בכל שלב, מהשיחה הראשונה ועד הרגעים האחרונים של המסע.",
    "about.belief.quality": "איכות על פני כמות",
    "about.belief.quality.desc": "כל חוויה מתוכננת אישית, עם תשומת לב קרובה לאיכות, נוחות וזרימה.",
    "about.belief.templates": "ללא תבניות",
    "about.belief.templates.desc": "אנחנו לא מאמינים בפתרונות אחידים. כל מסע הוא ייחודי.",
    "about.belief.precision": "דיוק ואכפתיות",
    "about.belief.precision.desc": "חוויית נסיעה נהדרת נוצרת דרך הקשבה, דיוק ואכפתיות אמיתית.",
    "about.promise.title": "ההבטחה שלנו אליך",
    "about.promise.p1": "אנחנו מעורבים בכל שלב, מהשיחה הראשונה ועד הרגעים האחרונים של המסע. אנחנו לא מעבירים אותך לצוות או נעלמים אחרי ההזמנה. אנחנו נשארים איתך, מוודאים שכל פרט מתגלגל כמתוכנן.",
    "about.promise.p2": "ההתחייבות שלנו היא ליצור חוויות נסיעה שמרגישות מאמץ, אישיות וזכירות. לא כי אנחנו עוקבים אחרי תסריט, אלא כי באמת אכפת לנו מהתוצאה.",
    "about.quote": "כשהלקוחות שלנו שמחים, אנחנו שמחים. זה המדד הפשוט ביותר להצלחה שאנחנו מכירים.",
    "about.cta.title": "בוא ניצור את הסיפור שלך",
    "about.cta.desc": "מוכן לחוות נסיעות אחרת? צור קשר ותן לנו לעצב מסע שהוא ייחודי לך.",
    "about.cta.button": "התחל לתכנן",
    
    // Personal Page
    "personal.page.tagline": "מותאם אישית עבורך",
    "personal.page.title": "נסיעות אישיות",
    "personal.page.description": "מסע שמשקף את סגנון החיים, ההעדפות והציפיות שלך – ללא תבניות או מסלולים מוגדרים מראש.",
    "personal.intro.title": "מדליק את הרוח שלך. מפנק את הנשמה שלך.",
    "personal.intro.p1": "אנחנו בולטים על ידי מסירה מושלמת של יעדים, מסלולים, לינות וכל מה שביניהם. הצוות יוצא הדופן שלנו מצטיין בהבנת הדרישות שלך, מתן המלצות מדויקות ויצירת תוכנית הנסיעה המושלמת. יש לנו את המומחיות להעלות כל חוויה לגבהים קסומים.",
    "personal.intro.p2": "אנחנו מבינים שכל יעד חלומות צריך להעביר נוחות יוקרתית ושלוות נפש, לא משנה לאן הדמיון שלך לוקח אותך.",
    "personal.intro.p3": "שותפות איתנו פותחת עולם של אפשרויות יוצאות דופן, שבו כל מסע מותאם לרצונות הייחודיים שלך. עם מומחיות אישית וקשרים פנימיים, אנחנו הולכים מעבר לרגיל ליצור בריחות שמרתקות ומעוררות השראה. ההרפתקה הבאה שלך מחכה, ואנחנו כאן לוודא שהיא עולה על החלומות הפרועים ביותר שלך.",
    "personal.quest.title": "משימה",
    "personal.quest.intro": "בין אם אתה מחפש הרפתקה מחוץ לרשת ברוקיז, חולם על זריחה במקדש הבודהיסטי הגדול בעולם, או פשוט משתוקק לנסיגת חוף טעימה, נעזור לך ליצור זכרונות לכל החיים.",
    "personal.quest.beach": "בריחות חוף",
    "personal.quest.beach.desc": "טבול את הבהונות בחולות הרכים של המלדיביים, ספוג את השמש בטורקס וקייקוס, או הרגע על החופים היוקרתיים של הריביירה הצרפתית.",
    "personal.quest.culture": "טבילות תרבותיות",
    "personal.quest.culture.desc": "גלה מקדשים עתיקים בקיוטו, טייל ברחובות ההיסטוריים של רומא, או גלה את המסורות התוססות של מרוקו.",
    "personal.quest.wine": "טעימות יין",
    "personal.quest.wine.desc": "טעם את הטעמים העשירים של טוסקנה, טייל בכרמי עמק נאפה, או גלה את יקבי ארגנטינה המפורסמים באזור מנדוזה.",
    "personal.quest.adventure": "משלחות הרפתקה",
    "personal.quest.adventure.desc": "טייל דרך שטחי הפרא של פטגוניה, צלול למים הצלולים של שונית המחסום הגדולה, או טפס לפסגות באלפים השוויצריים.",
    "personal.quest.wellness": "נסיגות בריאות",
    "personal.quest.wellness.desc": "התחדש בספא ברמה עולמית בבאלי, תרגל יוגה בהימלאיה, או מצא שלווה במעיינות חמים באיסלנד.",
    "personal.quest.culinary": "מסעות קולינריים",
    "personal.quest.culinary.desc": "שלוט באמנות המטבח הצרפתי בפריז, למד מנות איטלקיות אותנטיות בפירנצה, או גלה את הטעמים התוססים של תאילנד בבנגקוק.",
    "personal.memories.title": "יצירת זכרונות שהופכים למורשת",
    "personal.memories.desc": "נסיעות, במיטבן, הן חוויה אותנטית סוחפת שמחברת מטיילים להיסטוריה, לטבע, להרפתקאות ואחד לשני. בין אם אתה חוגג יום נישואין משמעותי, מתחבר כאב ובן תוך כדי חקירת קצה העולם, או חווה חג מולד בטירה חורפית אגדית, אנו יוצרים טיול שבונה את הקשרים החשובים הללו.",
    "personal.occasion.romantic": "בריחות רומנטיות",
    "personal.occasion.honeymoon": "ירח דבש",
    "personal.occasion.milestone": "אבני דרך משמעותיות",
    "personal.occasion.family": "איחודי משפחה רב-דוריים",
    "personal.occasion.friends": "הרפתקאות עם חברים",
    "personal.occasion.solo": "מסעות גילוי סולו",
    "personal.peace.title": "שקט נפשי, בכל צעד בדרך",
    "personal.peace.p1": "נסיעות צריכות להרגיש מאמץ. אנחנו נשארים מחוברים עם השותפים הגלובליים שלנו ועוקבים אחרי כל פרט מאחורי הקלעים כך שהטיול שלך יתגלגל בחלקלקות מתחילתו ועד סופו. מהתאמות חלקות ועד הדרכה מתחשבת ותמיכה בשטח, הצוות שלנו כאן לוודא שהמסע שלך מרגיש קל, מאובטח ומטופל לחלוטין.",
    "personal.peace.p2": "אנחנו לא רק מתכננים מסלולים – אנחנו מגנים על הזמן שלך, מעלים את החוויה שלך ונותנים לך שקט נפשי אמיתי לאן שלא תלך.",
    "personal.quote": "נסיעות אישיות הן למי שמעריך איכות, בהירות וחוויה רגועה ומנוהלת היטב – שנוצרה לחלוטין סביבם.",
    "personal.cta": "התחל לתכנן את המסע שלך",
    
    // Elite Journeys Page
    "elite.page.tagline": "יוקרה פרימיום",
    "elite.page.title": "מסעות עילית",
    "elite.page.description": "הרמה הגבוהה ביותר שלנו בעיצוב נסיעות, שנוצרה עבור לקוחות שמצפים לאישיות מלאה ולסודיות מוחלטת.",
    "elite.intro.title": "מצוינות ללא פשרות. יוקרה ללא גבולות.",
    "elite.intro.p1": "יוקרה פרימיום היא הרמה הגבוהה ביותר שלנו בעיצוב נסיעות. היא נוצרה עבור לקוחות שמצפים לאישיות מלאה, סודיות מוחלטת ומסע שמרגיש מאמץ מתחילתו ועד סופו.",
    "elite.intro.p2": "ברמה זו, כל חוויה נבנית מהיסוד. אין תבניות, אין מסלולים קבועים ואין פשרות. כל מסע מעוצב סביב ההעדפות, הקצב והחזון שלך, בין אם מדובר בווילות פרטיות, אתרי נופש בלעדיים, יעדים מרוחקים או מסלולים רב-ארציים.",
    "elite.intro.p3": "התהליך מתחיל בהבנה שלך. אנחנו לוקחים את הזמן ללמוד איך אתה אוהב לטייל, מה חשוב לך ואיך אתה מגדיר נוחות ויוקרה. משם, אנו מעצבים בזהירות חוויה שמרגישה טבעית, מאוזנת ומדויקת.",
    "elite.experience.title": "חוויית העילית",
    "elite.experience.intro": "יוקרה פרימיום מוגדרת על ידי איך שהכל זורם. תעופה פרטית, הגעות VIP, העברות חלקות, לינות נבחרות בקפידה וגישה בלעדית מתואמות בדייקנות ורוגע.",
    "elite.feature.aviation": "תעופה פרטית",
    "elite.feature.aviation.desc": "סידורי מטוס פרטי חלקים, טיפול VIP בשדה התעופה והעברות ישירות ליעד שלך ללא עיכובים או קהל.",
    "elite.feature.accommodations": "לינות בלעדיות",
    "elite.feature.accommodations.desc": "וילות פרטיות נבחרות בקפידה, סוויטות יוקרה ואתרי נופש בלעדיים שמציעים פרטיות ושירות ללא תחרות.",
    "elite.feature.concierge": "קונסיירז' אישי",
    "elite.feature.concierge.desc": "תמיכה ייעודית זמינה 24/7, מנהלת כל בקשה בדיוק ובסודיות לאורך כל המסע שלך.",
    "elite.feature.experiences": "חוויות מובחרות",
    "elite.feature.experiences.desc": "גישה לאירועים בלעדיים, צפיות פרטיות, סיורי מוזיאון לאחר שעות וחוויות שאינן זמינות לציבור.",
    "elite.feature.security": "אבטחה ופרטיות",
    "elite.feature.security.desc": "סידורי אבטחה מקיפים, תכנון נסיעות סודי וסודיות מלאה בכל שלב.",
    "elite.feature.logistics": "לוגיסטיקה חלקה",
    "elite.feature.logistics.desc": "כל העברה, הזמנה ותזמון מתואמים בדייקנות צבאית לחוויה מושלמת.",
    "elite.pillars.title": "עמודי התווך של נסיעות עילית",
    "elite.pillars.intro": "זו לא נסיעה שנבנית סביב יעדים בלבד. זו נסיעה שמעוצבת על ידי אווירה, נוחות ואמון. כל רגע הוא מכוון, כל בחירה נשקלת וכל חוויה מעוצבת להרגיש ייחודית לך.",
    "elite.pillar.personalization": "אישיות מלאה",
    "elite.pillar.discretion": "סודיות מוחלטת",
    "elite.pillar.execution": "ביצוע מאמץ",
    "elite.pillar.quality": "איכות ללא פשרות",
    "elite.pillar.support": "תמיכה ייעודית 24/7",
    "elite.pillar.access": "גישה ברמה עולמית",
    "elite.confidence.title": "ביטחון בכל צעד",
    "elite.confidence.p1": "השירות אישי וזמין בכל עת. לקוחות מקבלים תמיכה ייעודית לפני, במהלך ואחרי המסע, עם תשומת לב מלאה לתזמון, פרטיות וצרכים אישיים. סודיות ואמינות אף פעם לא אופציונליות.",
    "elite.confidence.p2": "הצוות שלנו מנהל כל פרט מאחורי הקלעים, מאפשר לך להתמקד רק בחוויה עצמה. מהשיחה הראשונה ועד הרגעים האחרונים של המסע שלך, הכל מטופל בדיוק ובאכפתיות.",
    "elite.quote": "יוקרה פרימיום היא ביטחון. לדעת שהכל מטופל כראוי, בשקט ולפי הסטנדרט הגבוה ביותר.",
    "elite.cta": "עצב את מסע העילית שלך",
    
    // Private Flights Page
    "flights.page.tagline": "תעופה פרטית",
    "flights.page.title": "טיסות פרטיות",
    "flights.page.description": "סיוע מקצועי מסביב לשעון בסידור טיסות פרטיות, מותאמות במדויק לכל לקוח.",
    "flights.intro.title": "הזמן יקר. נסיעות צריכות להיות חלקות.",
    "flights.intro.p1": "טיסות פרטיות מעוצבות עבור לקוחות שמעריכים זמן, פרטיות ואמינות מלאה. כחלק מהשירותים שלנו, אנו מספקים סיוע מקצועי מסביב לשעון בסידור טיסות פרטיות, מותאמות במדויק לכל לקוח.",
    "flights.intro.p2": "אנו עובדים עם שותפי תעופה מהימנים ומפעילים נבחרים בקפידה, מה שמאפשר לנו להציע גישה למגוון רחב של מטוסים פרטיים לטיסות קצרות וארוכות. כל פרט מנוהל כדי להבטיח שהמסע שלך יהיה חלק, נוח ומדויק בלוח הזמנים.",
    "flights.service.title": "שירות מלא",
    "flights.service.intro": "מהפנייה הראשונה, אנו מנהלים את כל התהליך. כל היבט של הטיסה הפרטית שלך מטופל בזהירות ובבהירות, מאפשר לחוויה להישאר רגועה וחלקה.",
    "flights.service.aircraft": "בחירת מטוס",
    "flights.service.aircraft.desc": "גישה למגוון רחב של מטוסים פרטיים לטיסות קצרות וארוכות, מותאמים לצרכים הספציפיים שלך.",
    "flights.service.scheduling": "תזמון טיסות",
    "flights.service.scheduling.desc": "זמני המראה גמישים שעובדים סביב לוח הזמנים שלך, לא להפך.",
    "flights.service.routing": "תכנון מסלול",
    "flights.service.routing.desc": "ניתוב מיטוב ליעילות, נוחות וזמן נסיעה מינימלי.",
    "flights.service.ground": "טיפול קרקעי",
    "flights.service.ground.desc": "הגעות ויציאות VIP, טרמינלים פרטיים ותיאום קרקעי חלק.",
    "flights.service.special": "בקשות מיוחדות",
    "flights.service.special.desc": "קייטרינג, שירותי טיסה ונגיעות אישיות מטופלים בדיוק.",
    "flights.service.security": "סידורי אבטחה",
    "flights.service.security.desc": "סודיות מלאה ותיאום אבטחה כנדרש.",
    "flights.commitment.title": "ההתחייבות שלנו אליך",
    "flights.commitment.p1": "כל טיסה מתוכננת עם תשומת לב קפדנית לבטיחות, נוחות, סודיות ותזמון. זמן הוא גורם קריטי בתעופה פרטית. אנו שמים דגש חזק על דייקנות, תיאום ברור וביצוע מדויק.",
    "flights.commitment.p2": "השירות שלנו זמין 24/7. לקוחות מקבלים תמיכה רציפה לפני, במהלך ואחרי הטיסה, עם נקודת קשר ישירה ומגיבה בכל עת.",
    "flights.commitment.247": "זמינות 24/7",
    "flights.commitment.contact": "נקודת קשר ישירה",
    "flights.commitment.punctuality": "דייקנות קפדנית",
    "flights.commitment.discretion": "סודיות מלאה",
    "flights.commitment.partners": "שותפי תעופה מהימנים",
    "flights.commitment.coordination": "תיאום חלק",
    "flights.beyond.title": "מעבר ליוקרה",
    "flights.beyond.p1": "תעופה פרטית היא לא רק יוקרה. זה יעילות, אמון וביטחון באנשים שמנהלים את המסע שלך. התפקיד שלנו הוא לוודא שכל טיסה מטופלת מקצועית ובזמן.",
    "flights.beyond.p2": "מהמראה ועד הנחיתה, כל פרט מנוהל כדי להבטיח שהטיסה פועלת בדיוק כמתוכנן. הזמן שלך חשוב, ואנחנו מתייחסים אליו בכבוד שהוא ראוי לו.",
    "flights.quote": "יעילות, אמון וביטחון – היסודות של כל טיסה שאנו מסדרים.",
    "flights.cta": "בירור על טיסות פרטיות",
    
    // Boutique Page
    "boutique.page.tagline": "חוויות מובחרות",
    "boutique.page.title": "חוויית בוטיק",
    "boutique.page.description": "מסעות מעוצבים ביד הכוללים יוקרת מדבר, הרפתקאות אלפיניות, גילוי ים תיכוני וטבילה קולינרית.",
    "boutique.intro.title": "מסעות שנוצרים בכוונה ובאכפתיות.",
    "boutique.intro.p1": "חוויות הבוטיק שלנו אינן מסלולים המיוצרים בהמוניהם. כל מסע מעוצב בקפידה להציע עומק, אותנטיות וחיבור ליעד שהולך מעבר לפני השטח.",
    "boutique.intro.p2": "מהשקט של המדבר הערבי ועד הכבישים המפותלים של האלפים, מהטעמים של יוון ועד הגבעות המתגלגלות של טוסקנה – כל חוויה נבנית סביב איכות, דיוק וההעדפות האישיות שלך.",
    "boutique.uae.title": "יוקרת מדבר איחוד האמירויות",
    "boutique.uae.subtitle": "אלגנטיות מודרנית פוגשת שקט מדברי",
    "boutique.uae.intro": "איחוד האמירויות מציע שילוב מעודן של אלגנטיות מודרנית והשקט הנצחי של המדבר. חוויה זו מעוצבת עבור מטיילים שמצפים לדיוק, סודיות ומסע מנוהל לחלוטין מתחילתו ועד סופו.",
    "boutique.uae.content": "מרגע ההגעה, כל פרט מטופל. העברות פרטיות, טיפול VIP בשדה התעופה ותיאום חלק מבטיחים התחלה חלקה ורגועה. המסע ממשיך מעבר לעיר, עם אפשרות של העברה במסוק פרטי ישירות אל המדבר. אורחים מגיעים בדיסקרטיות לאל מהה דזרט ריזורט אנד ספא, מקלט מבודד השוכן עמוק בתוך הדיונות. וילות פרטיות עם בריכות אישיות, נופי מדבר נרחבים ופרטיות מלאה יוצרים אווירה של יוקרה שקטה.",
    "boutique.uae.closing": "חוויה זו היא לא רק יוקרה. זה שקט נפשי, פרטיות והידיעה שהכל מנוהל באכפתיות, דיוק וכבוד לזמן שלך.",
    "boutique.uae.h1": "העברה במסוק פרטי למקלט מדברי",
    "boutique.uae.h2": "וילות פרטיות עם בריכות אישיות",
    "boutique.uae.h3": "סיוע אישי ואבטחה 24/7",
    "boutique.uae.h4": "טיפול VIP בשדה התעופה והעברות",
    "boutique.uae.h5": "פרטיות וסודיות מלאות",
    "boutique.alpine.title": "הרפתקה אלפינית",
    "boutique.alpine.subtitle": "חוויית נהיגה באוסטריה ואיטליה",
    "boutique.alpine.intro": "חוויה זו מעוצבת למי שמעריך ביצועים, נוף וחופש תנועה מוחלט. מסע אלפיני פרטי דרך אוסטריה ואיטליה, המשלב כבישי הרים אייקוניים עם מכוניות ספורט בביצועים גבוהים.",
    "boutique.alpine.content": "כל מסע נבנה בהתאמה אישית. מסלולים, קצב נהיגה, יעדים וחוויות מתוכננים לפי העדפות אישיות. האלפים מציעים כמה מכבישי הנהיגה המרשימים ביותר באירופה. מעברי הרים מפותלים, מתחים פתוחים, נופים דרמטיים ועמקים שקטים יוצרים חוויית נהיגה שמרגישה עוצמתית ומעודנת. רכבים פרימיום, לוגיסטיקה, לינות, אוכל ותיאום יומיומי מנוהלים לחלוטין.",
    "boutique.alpine.closing": "זה לא סיור מכוניות סטנדרטי. זהו מסע אלפיני מובחר בקפידה, שנבנה סביב איכות, דיוק והנאה – שילוב של נהיגה, נוף, שירות ואמון.",
    "boutique.alpine.h1": "רכבי פרימיום בביצועים גבוהים",
    "boutique.alpine.h2": "מעברי הרים אייקוניים ומסלולים נופיים",
    "boutique.alpine.h3": "לודג'ים ומלונות אלפיניים יוקרתיים",
    "boutique.alpine.h4": "לוגיסטיקה ותיאום מנוהלים לחלוטין",
    "boutique.alpine.h5": "מסלולים בנויים בהתאמה אישית",
    "boutique.mediterranean.title": "גילוי ים תיכוני",
    "boutique.mediterranean.subtitle": "יוון דרך טעם ואלגנטיות",
    "boutique.mediterranean.intro": "גילוי ים תיכוני הוא הזמנה לחוות את יוון דרך טעם, אלגנטיות ויוקרה שקטה. מסע זה משלב טעמים מקומיים אותנטיים עם הכנסת אורחים מעודנת, מעוצב למטיילים שמעריכים עומק, נוחות ופרטים מתחשבים.",
    "boutique.mediterranean.content": "החוויה מתחילה עם הגעה לשדה תעופה פרטי בצפון יוון, מבטיחה פרטיות ומעבר חלק. בימים הבאים, האזור נפתח בהדרגה. ביקורים פרטיים ביקבים מקומיים, אחוזות שמן זית אותנטיות ועצירות קולינריות נבחרות בקפידה יוצרים חיבור עמוק לארץ. ארוחות בהנחיית שף מדגישות מרכיבים מקומיים, טעמים עונתיים ופשטות ים תיכונית במיטבה.",
    "boutique.mediterranean.closing": "זה לא רק טיול דרך יוון. זהו מסע ים תיכוני מעודן, שנבנה סביב טעם, אמון וסטנדרטים ללא פשרות.",
    "boutique.mediterranean.h1": "הגעה לשדה תעופה פרטי בצפון יוון",
    "boutique.mediterranean.h2": "לינה במלונות בוטיק",
    "boutique.mediterranean.h3": "ביקורים פרטיים ביקבים ואחוזות זיתים",
    "boutique.mediterranean.h4": "ארוחות עונתיות בהנחיית שף",
    "boutique.mediterranean.h5": "מיקומים נסתרים ומפגשים בלעדיים",
    "boutique.tuscany.title": "טבילה קולינרית",
    "boutique.tuscany.subtitle": "הטעמים האותנטיים של טוסקנה",
    "boutique.tuscany.intro": "טוסקנה היא מהות המסורת הקולינרית האיטלקית. חוויה זו מציעה מסע אינטימי דרך טוסקנה, שבו אוכל, נוף ותרבות מתאחדים באיזון מושלם.",
    "boutique.tuscany.content": "אורחים שוהים במלונות בוטיק נבחרים בקפידה ואחוזות כפריות, מוקפים בגבעות מתגלגלות, כרמים וחורשות זיתים. החוויה נבנית סביב טעם ואותנטיות. שיעורי בישול פרטיים, ביקורים ביקבים בבעלות משפחתית, יצרני שמן זית וסדנאות אומנות מציעים מבט מאחורי הקלעים לתוך המורשת הקולינרית הטוסקנית. טעימות יין, ציד כמהין וארוחות ארוכות ולא ממהרות מהוות את קצב המסע.",
    "boutique.tuscany.closing": "טבילה קולינרית בטוסקנה היא לא על עודף. זה על איכות, עומק והבנת איטליה דרך הטעמים, הנופים והאנשים שלה.",
    "boutique.tuscany.h1": "מלונות בוטיק ואחוזות כפריות",
    "boutique.tuscany.h2": "שיעורי בישול פרטיים עם שפים מקומיים",
    "boutique.tuscany.h3": "ביקורים ביקבים בבעלות משפחתית",
    "boutique.tuscany.h4": "חוויות ציד כמהין",
    "boutique.tuscany.h5": "גילויי סדנאות אומנות",
    "boutique.quote": "כל חוויית בוטיק היא הבטחה – של איכות, אותנטיות ורגעים שנשארים איתך הרבה אחרי שהמסע מסתיים.",
    "boutique.cta": "צור את חוויית הבוטיק שלך",
    
    // Contact Page
    "contact.page.tagline": "התחל את המסע שלך",
    "contact.page.title": "צור קשר",
    "contact.page.description": "אנחנו כאן לעצב את המסע הבא שלך בדיוק, אכפתיות ונגיעה אישית. בין אם אתה חולם על איים יווניים, וילות איטלקיות או נסיגות אסייתיות – שתף כמה פרטים כדי לעזור לנו להתאים את החוויה שלך.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  // Keep the site layout consistent (LTR) for all languages.
  // Hebrew text changes, but the layout should NOT flip.
  const isRTL = false;

  useEffect(() => {
    document.documentElement.setAttribute("dir", "ltr");
    document.documentElement.style.direction = "ltr";

    if (document.body) {
      document.body.setAttribute("dir", "ltr");
      document.body.style.direction = "ltr";
    }

    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
